#Jekyll Configuration
name: BookCellent
description: Excellent Books
url: "https://www.bookcellent.com"
markdown: GFM
plugins:
  - jemoji
  - jekyll-remote-theme
#remote_theme: oinam/oinam-jekyll
remote_theme: pages-themes/minimal@v0.2.0
