[project]
name = "bookcellent"
version = "0.1.0"
description = "Excellent Books"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["tqdm", "requests"]

[project.optional-dependencies]
test = ["pytest"]
